// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl59beIK18vV3ZCFbJBMenYdQcIehI7uo',
    appId: '1:19959687372:web:f755a88f5140cb74323a69',
    messagingSenderId: '19959687372',
    projectId: 'ertyu-yhd0298',
    authDomain: 'ertyu-yhd0298.firebaseapp.com',
    storageBucket: 'ertyu-yhd0298.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAVwTxagz7d1ulbjI20WS-N5PU_jKmMo',
    appId: '1:19959687372:android:125fbdfa06b76045323a69',
    messagingSenderId: '19959687372',
    projectId: 'ertyu-yhd0298',
    storageBucket: 'ertyu-yhd0298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1NzdNpvb7v0ymGWUpjB7p3wHgJda3YI',
    appId: '1:19959687372:ios:2a5b4168aa30cf53323a69',
    messagingSenderId: '19959687372',
    projectId: 'ertyu-yhd0298',
    storageBucket: 'ertyu-yhd0298.firebasestorage.app',
    iosClientId: '19959687372-a3jkdmvr2k74hm8i6m7pv96pk07bp64k.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq1NzdNpvb7v0ymGWUpjB7p3wHgJda3YI',
    appId: '1:19959687372:ios:2a5b4168aa30cf53323a69',
    messagingSenderId: '19959687372',
    projectId: 'ertyu-yhd0298',
    storageBucket: 'ertyu-yhd0298.firebasestorage.app',
    iosClientId: '19959687372-a3jkdmvr2k74hm8i6m7pv96pk07bp64k.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl59beIK18vV3ZCFbJBMenYdQcIehI7uo',
    appId: '1:19959687372:web:893ceb60038bb89c323a69',
    messagingSenderId: '19959687372',
    projectId: 'ertyu-yhd0298',
    authDomain: 'ertyu-yhd0298.firebaseapp.com',
    storageBucket: 'ertyu-yhd0298.firebasestorage.app',
  );
}
